version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Running test
          command: |
      echo Running test
      mkdir -p /tmp/test-results
      make test


            